### PR TITLE
fix: [#189] Fix .hamlc is unexpectedly processed by JstProcessor

### PR DESCRIPTION
**Pull request by voducvu**
Separate mimetype for .hamlc and .jst.hamlc so that the hamlc is only processed by HamlCoffeeAssets::Transformer and jst.haml is processed by ::HamlCoffeeAssets::Transformer and JstProcessor

### CODE REVIEW

**Review by mathieujobin — APPROVED** [review]
@phenchaw Can you have a look at this patch please?

**Review by mathieujobin — COMMENTED** [review]
appears to work with Sprockets 3 but not 4 ?!?

please have a look at the tests results

**Comment by mathieujobin** [comment]
@voducvu seems like something is broken with sprockets 4

can you please have a look ?

**Comment by voducvu** [comment]
@mathieujobin Sorry, i'm quite busy now. I'll look into it when I have more time.

**Comment by ashkulz** [comment]
Depending on which one gets merged first, this PR or #191 may need to be adjusted since there's a conflict.

**Comment by ashkulz** [comment]
@mathieujobin please see 3922a3cb741f7db3532c0d64a2a90a860f663fdd -- it's an issue with Rack 3 compatibility and [makes the CI green](https://github.com/teamsimplepay/haml_coffee_assets/actions/runs/10007041498). Should I make it as a separate PR?

**Review by mathieujobin — CHANGES_REQUESTED** [review]
I assume this was equivalent to #191 but we don't need both right?
I'm surprise to see a merge conflicts between the two.

please open a new PR if what is merged is incomplete. 

thanks

**Comment by voducvu** [comment]
@mathieujobin it's not equivalent to #191. Please help me merge this one also.

**Pull request closed without merging**
