### PR TITLE
[#189] Fix .hamlc is processed by jst unexpectedly

### PR DESCRIPTION
**Pull request by voducvu**
Separate mimetype for .hamlc and .jst.hamlc so that the hamlc is only processed by HamlCoffeeAssets::Transformer and jst.haml is processed by ::HamlCoffeeAssets::Transformer and JstProcessor

### CODE REVIEW

**Comment by voducvu** [comment]
@mathieujobin please help me merge this PR

**Comment by mathieujobin** [comment]
Sure I can only release tomorrow though

**Review by mathieujobin — APPROVED** [review]

**Comment by voducvu** [comment]
@mathieujobin could you please release it asap so that my team can release our bug fix

**Comment by mathieujobin** [comment]
done

**Pull request merged**
