### PR TITLE
Updates to support Rails 6

### PR DESCRIPTION
**Pull request by mrpinsky**
As of https://github.com/rails/rails/pull/34952, the fallback for nil buffer was moved up to the method call's default argument. The `nil` default here is passed to the original method (`old_render`), preventing the default from being applied. This meant that any template going through this monkey patch on Rails 6 blew up when it tried to call methods on the buffer.

### CODE REVIEW

**Comment by mrpinsky** [comment]
To make it easier to get CI passing, are you okay with dropping support for versions of Ruby and Rails that are out of LTS?

**Comment by masterkain** [comment]
project is dead I think

**Comment by mathieujobin** [comment]
@mrpinsky I vote yes

lets remove rails 4.2 and below

**Comment by mrpinsky** [comment]
Unfortunately I no longer have access to `polleverywhere`. @hakusaro or @andrewhampton, could you take over this PR?

**Comment by mathieujobin** [comment]
This error looks legit

```
NoMethodError:

       undefined method `pathname' for #<Sprockets::Asset:0x0000000004d21550>
```

Maybe we should do baby steps, on my branch tests are still passing for ruby 2.4 but not for ruby 2.5 complaining about some manifst.js file? That does not sound ruby related, so it does not make sense. Especially on the rails 4.2

**Comment by mathieujobin** [comment]
rails 6.0 and 6.1 added via https://github.com/emilioforrer/haml_coffee_assets/pull/180

please open a different PR if necessary

**Pull request closed without merging**
